version: "3"

tasks:
  generate:
    desc: "Generate Go code from sso.proto"
    cmds:
      - protoc --proto_path=proto --go_out=gen/go --go_opt=paths=source_relative --go-grpc_out=gen/go --go-grpc_opt=paths=source_relative proto/sso/sso.proto
